"""empty message

Revision ID: 046d1b5b151b
Revises: f3e476b01411
Create Date: 2019-04-11 20:49:43.679673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046d1b5b151b'
down_revision = 'f3e476b01411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_counts', sa.Column('total_all', sa.Integer(), nullable=False))
    op.add_column('traffic_counts', sa.Column('total_hgv', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_counts', 'total_hgv')
    op.drop_column('traffic_counts', 'total_all')
    # ### end Alembic commands ###
