"""empty message

Revision ID: 1929bfab19a6
Revises: f6c52a737541
Create Date: 2019-04-12 19:21:10.568666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1929bfab19a6'
down_revision = 'f6c52a737541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('year_link_combo', 'traffic_counts', ['year', 'link'])
    op.drop_constraint('cp_year_combo', 'traffic_counts', type_='unique')
    op.drop_column('traffic_counts', 'cp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_counts', sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('cp_year_combo', 'traffic_counts', ['cp', 'year'])
    op.drop_constraint('year_link_combo', 'traffic_counts', type_='unique')
    # ### end Alembic commands ###
