"""empty message

Revision ID: acb3601a294c
Revises: 
Create Date: 2019-04-11 00:15:39.619528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb3601a294c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('road_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('junctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_junction', sa.Integer(), nullable=True),
    sa.Column('end_junction', sa.Integer(), nullable=True),
    sa.Column('road_category', sa.Integer(), nullable=True),
    sa.Column('local_authority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_junction'], ['junctions.id'], ),
    sa.ForeignKeyConstraint(['local_authority'], ['authorities.id'], ),
    sa.ForeignKeyConstraint(['road_category'], ['road_categories.id'], ),
    sa.ForeignKeyConstraint(['start_junction'], ['junctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('link', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('northing', sa.Integer(), nullable=False),
    sa.Column('easting', sa.Integer(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('pedal_cycles', sa.Integer(), nullable=False),
    sa.Column('motor_cycles', sa.Integer(), nullable=False),
    sa.Column('cars_taxis', sa.Integer(), nullable=False),
    sa.Column('buses_coaches', sa.Integer(), nullable=False),
    sa.Column('light_goods', sa.Integer(), nullable=False),
    sa.Column('v2_rigid_hgv', sa.Integer(), nullable=False),
    sa.Column('v3_rigid_hgv', sa.Integer(), nullable=False),
    sa.Column('v4_rigid_hgv', sa.Integer(), nullable=False),
    sa.Column('v4_artic_hgv', sa.Integer(), nullable=False),
    sa.Column('v5_artic_hgv', sa.Integer(), nullable=False),
    sa.Column('v6_artic_hgv', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_counts')
    op.drop_table('links')
    op.drop_table('junctions')
    op.drop_table('authorities')
    op.drop_table('roads')
    op.drop_table('road_categories')
    op.drop_table('regions')
    # ### end Alembic commands ###
