"""empty message

Revision ID: f3e476b01411
Revises: bc0a84236cd1
Create Date: 2019-04-11 20:38:20.753544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e476b01411'
down_revision = 'bc0a84236cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_counts', 'total_vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_counts', sa.Column('total_vehicles', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
