"""empty message

Revision ID: f6c52a737541
Revises: e2f5d814e2e9
Create Date: 2019-04-11 21:15:09.612149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c52a737541'
down_revision = 'e2f5d814e2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_authority_region_combo', 'authorities', ['name', 'region'])
    op.create_unique_constraint('cp_year_combo', 'traffic_counts', ['cp', 'year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cp_year_combo', 'traffic_counts', type_='unique')
    op.drop_constraint('unique_authority_region_combo', 'authorities', type_='unique')
    # ### end Alembic commands ###
